In [2]:
import numpy as np

In [2]:
# Membuat Array 1D

hewan = np.array(['Kucing','Rakun','Jerapah'])
print(hewan)

['Kucing' 'Rakun' 'Jerapah']


Kode menggunakan NumPy untuk membuat dan mencetak array 1D (satu dimensi). Pertama, array hewan dibuat dengan fungsi np.array(), yang berisi tiga elemen string: `Kucing`, `Rakun`, dan `Jerapah`. Kemudian, perintah print(hewan) digunakan untuk menampilkan isi array tersebut ke output.

In [4]:
# Array 2D
hewan = np.array([['Kucing','Rakun','Jerapah'], ['Serigala', 'Musang', 'Kodok']])
print(hewan)

[['Kucing' 'Rakun' 'Jerapah']
 ['Serigala' 'Musang' 'Kodok']]


Kode membuat array 2D menggunakan NumPy, di mana variabel hewan berisi dua baris dengan masing-masing tiga elemen string. Saat print(hewan) dijalankan, array ditampilkan dalam format matriks dengan baris pertama berisi `Kucing`, `Rakun`, `Jerapah`, dan baris kedua berisi `Serigala`, `Musang`, `Kodok`.

In [5]:
# Menambahkan Elemen Array

a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.append(a,b))

[1 2 3 4 5 6]


Kode menggunakan **NumPy** untuk menambahkan elemen dari array `b` ke array `a` dengan fungsi `np.append()`. Array `a` berisi `[1,2,3]` dan array `b` berisi `[4,5,6]`, lalu `np.append(a, b)` menggabungkan keduanya menjadi `[1,2,3,4,5,6]`, yang kemudian ditampilkan dengan `print()`.

In [10]:
x = np.array([[1,2], [3,4]])
x = np.append(x, [[5,6]], axis=0)
print("Array 2D\n", x)

Array 2D
 [[1 2]
 [3 4]
 [5 6]]


Kode menggunakan **NumPy** untuk menambahkan baris baru ke dalam **array 2D**. Awalnya, `x` adalah array **2×2** dengan elemen `[[1,2], [3,4]]`. Fungsi `np.append(x, [[5,6]], axis=0)` menambahkan baris `[5,6]` di bawahnya, sehingga `x` menjadi `[[1,2], [3,4], [5,6]]`, yang kemudian dicetak dengan `print()`.

In [14]:
# Menghapus Elemen

x = np.array([[1,2], [3,4]])
x = np.delete(x, 0, axis=0)
print("Array 2D\n", x)

Array 2D
 [[3 4]]


Kode menggunakan **NumPy** untuk menghapus elemen dari **array 2D**. Awalnya, `x` adalah array `[[1,2], [3,4]]`. Fungsi `np.delete(x, 0, axis=0)` menghapus baris pertama (indeks 0), sehingga `x` menjadi `[[3,4]]`, yang kemudian dicetak dengan `print()`.

In [15]:
# Operasi Array

arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
print("Penjumlahan", arr_a + arr_b)
print("Pengurangan", arr_a - arr_b)
print("Perkalian", arr_a * arr_b)
print("Pembagian", arr_a / arr_b)

Penjumlahan [5 7 9]
Pengurangan [-3 -3 -3]
Perkalian [ 4 10 18]
Pembagian [0.25 0.4  0.5 ]


Kode menggunakan **NumPy** untuk melakukan operasi aritmatika pada dua **array 1D**. `arr_a` berisi `[1,2,3]` dan `arr_b` berisi `[4,5,6]`. Operasi dilakukan secara **elemen-per-elemen**, sehingga:  

- **Penjumlahan** menghasilkan `[5,7,9]`  
- **Pengurangan** menghasilkan `[-3,-3,-3]`  
- **Perkalian** menghasilkan `[4,10,18]`  
- **Pembagian** menghasilkan `[0.25, 0.4, 0.5]`  

Hasilnya kemudian ditampilkan dengan `print()`.

In [17]:
x = np.array([1,2,3,4,5,6])
y = np.array([[5,6],[7,8]])

if x.size == y.size:
    print("Ukuran array sama")
else:
    print("Ukuran array tidak sama")

Ukuran array tidak sama


Kode menggunakan **NumPy** untuk membandingkan ukuran dua array, yaitu `x` yang merupakan **array 1D** dengan enam elemen `[1,2,3,4,5,6]`, dan `y` yang merupakan **array 2D** berukuran **2×2** dengan elemen `[[5,6],[7,8]]`. Fungsi `x.size` dan `y.size` digunakan untuk menghitung jumlah elemen di masing-masing array. Karena `x` memiliki **6 elemen** dan `y` hanya memiliki **4 elemen**, kondisi `if` akan mencetak `"Ukuran array tidak sama"`.

In [28]:
def input_data():
    n = int(input("Masukkan jumlah data: "))
    data = []
    for i in range(n):
        value = float(input(f"Masukkan data ke-{i+1} :"))
        data.append(value)

    return data

print("Program Menghitung Mean, Median, dan Standar deviasi")

data = input_data()

mean_value = np.mean(data)
median_value = np.median(data)
std_value = np.std(data)

print("\nHasil Perhitungan:")
print(f"Data yang dimasukkan: {data}")
print(f"Mean\t\t: {mean_value}")
print(f"Median\t\t: {median_value}")
print(f"Standar Deviasi\t: {std_value}")

Program Menghitung Mean, Median, dan Standar deviasi

Hasil Perhitungan:
Data yang dimasukkan: [2.0, 1.0, 2.0]
Mean		: 1.6666666666666667
Median		: 2.0
Standar Deviasi	: 0.4714045207910317


Kode adalah program Python menggunakan **NumPy** untuk menghitung **mean (rata-rata), median, dan standar deviasi** dari sekumpulan data yang dimasukkan pengguna. Fungsi `input_data()` meminta pengguna memasukkan sejumlah data yang kemudian disimpan dalam list `data`. Setelah data diperoleh, fungsi **NumPy** digunakan untuk menghitung **mean (`np.mean()`), median (`np.median()`), dan standar deviasi (`np.std()`)**. Hasil perhitungan kemudian ditampilkan dalam format yang rapi.

In [ ]:
def tambah_mahasiswa(data):
    nama = input("Nama : ")
    nim = input("NIM : ")

    try:
        nilai = float(input("Nilai : "))
        thn = int(input("Tahun Masuk : "))
    except ValueError:
        print("Nilai dan Tahun Masuk harus berupa angka!")
        return data
    return np.append(data, np.array([(nama, nim, nilai, thn)], dtype=data.dtype))

def tampilkan_mahasiswa(data):
    data_len = len(data)
    if data_len == 0:
        print("Kosong")
        return

    for row in data:
        print(f"Nama\t\t: {row['Nama']}")
        print(f"NIM\t\t: {row['NIM']}")
        print(f"Nilai\t\t: {row['Nilai']}")
        print(f"Tahun Masuk\t: {row['Tahun Masuk']}\n")

def statistik_nilai(data):
    if len(data) == 0:
        print("Kosong")
        return

    print("\nStatistik Nilai:")
    print(f"Nilai Tertinggi : {np.max(data['Nilai'])}")
    print(f"Nilai Terendah  : {np.min(data['Nilai'])}")
    print(f"Nilai Rata-rata : {np.mean(data['Nilai']):.2f}")

def cari_mahasiswa(data):
    search = input("NIM / Nama Mahawsiswa : ")
    search_result = np.array([],dtype=data.dtype)

    for row in data:
        if search == row["Nama"] or search == row["NIM"]:
            search_result = np.append(search_result, row)

    tampilkan_mahasiswa(search_result)

data = np.array([], dtype={'names'  :("Nama", "NIM", "Nilai", "Tahun Masuk"),
                           "formats":("U50", "U15", "f4", "i4")})

while True:
    print("Menu:")
    print("1. Tambah Mahasiswa")
    print("2. Tampilkan Mahasiswa")
    print("3. Statistik Nilai")
    print("4. Cari Mahasiswa")
    print("5. Keluar")

    key = input("Pilih menu: ")

    if key == '1':
        data = tambah_mahasiswa(data)
    elif key == '2':
        tampilkan_mahasiswa(data)
    elif key == '3':
        statistik_nilai(data)
    elif key == '4':
        cari_mahasiswa(data)
    elif key == '5':
        break

Program sederhana untuk mengelola data mahasiswa menggunakan **NumPy** sebagai struktur data utama. Program ini memungkinkan pengguna untuk menambahkan mahasiswa, menampilkan daftar mahasiswa, melihat statistik nilai, mencari mahasiswa berdasarkan **NIM atau nama**, serta keluar dari program melalui menu interaktif berbasis **input pengguna**.

Fungsi `tambah_mahasiswa(data)` meminta pengguna memasukkan data mahasiswa, termasuk **Nama, NIM, Nilai, dan Tahun Masuk**, kemudian menambahkannya ke dalam array **NumPy** menggunakan `np.append()`. Fungsi `tampilkan_mahasiswa(data)` menampilkan semua data mahasiswa yang tersimpan dalam array, jika ada, dengan format yang terstruktur. Jika tidak ada data, akan muncul pesan "Kosong".

Fungsi `statistik_nilai(data)` menghitung **nilai tertinggi, nilai terendah, dan nilai rata-rata** dari seluruh mahasiswa yang terdaftar, menggunakan fungsi `np.max()`, `np.min()`, dan `np.mean()`. Jika tidak ada data, akan muncul pesan "Data Kosong". Fungsi `cari_mahasiswa(data)` memungkinkan pencarian mahasiswa berdasarkan **Nama atau NIM**, dan hasil pencarian akan ditampilkan menggunakan `tampilkan_mahasiswa()`.

In [35]:
def tambah_barang(data):
    nama = input("Nama Barang : ")
    kode = input("Kode Barang : ")

    try:
        jumlah = int(input("Jumlah : "))
        harga = float(input("Harga Per Unit : "))
    except ValueError:
        print("Jumlah dan Harga harus berupa angka!")
        return data

    return np.append(data, np.array([(nama, kode, jumlah, harga)], dtype=data.dtype))

def tampilkan_barang(data):
    data_len = len(data)
    if data_len == 0:
        print("Kosong")
        return

    for row in data:
        print(f"Nama Barang\t: {row['NamaBarang']}")
        print(f"Kode Barang\t: {row['KodeBarang']}")
        print(f"Jumlah\t\t: {row['Jumlah']}")
        print(f"Harga Per Unit\t: {row['HargaPerUnit']}\n")

def inventaris(data):
    if len(data) == 0:
        print("Data Kosong")
        return

    total = sum(row["HargaPerUnit"] * row["Jumlah"] for row in data)
    print(f"\nTotal Nilai Inventaris: {total}")

def cari_barang(data):
    search = input("Nama / Kode Barang : ")
    search_result = np.array([],dtype=data.dtype)

    for row in data:
        if search == row["NamaBarang"] or search == row["KodeBarang"]:
            search_result = np.append(search_result, row)

    tampilkan_barang(search_result)

data = np.array([], dtype={'names'  :("NamaBarang", "KodeBarang", "Jumlah", "HargaPerUnit"),
                           "formats":("U50", "U15", "i8", "f8")})

while True:
    print("Menu:")
    print("1. Tambah Barang")
    print("2. Tampilkan Barang")
    print("3. Total Nilai Inventaris")
    print("4. Cari Barang")
    print("5. Keluar")

    key = input("Pilih menu: ")

    if key == '1':
        data = tambah_barang(data)
    elif key == '2':
        tampilkan_barang(data)
    elif key == '3':
        inventaris(data)
    elif key == '4':
        cari_barang(data)
    elif key == '5':
        break

Nama Barang		: Laptop
Kode Barang		: LPT123
Jumlah		: 5
Harga Per Unit	: 7500000.0

Nama Barang		: Printer
Kode Barang		: PRT456
Jumlah		: 2
Harga Per Unit	: 1500000.0

Nama Barang		: Mouse
Kode Barang		: MS789
Jumlah		: 10
Harga Per Unit	: 250000.0

Nama Barang		: Monitor
Kode Barang		: MN345
Jumlah		: 3
Harga Per Unit	: 2000000.0

Menu:
1. Tambah Barang
2. Tampilkan Barang
3. Total Nilai Inventaris
4. Cari Barang
5. Keluar
Menu:
1. Tambah Barang
2. Tampilkan Barang
3. Total Nilai Inventaris
4. Cari Barang
5. Keluar

Total Nilai Inventaris: 49000000.0
Menu:
1. Tambah Barang
2. Tampilkan Barang
3. Total Nilai Inventaris
4. Cari Barang
5. Keluar
Nama Barang		: Mouse
Kode Barang		: MS789
Jumlah		: 10
Harga Per Unit	: 250000.0

Menu:
1. Tambah Barang
2. Tampilkan Barang
3. Total Nilai Inventaris
4. Cari Barang
5. Keluar
Menu:
1. Tambah Barang
2. Tampilkan Barang
3. Total Nilai Inventaris
4. Cari Barang
5. Keluar


Program manajemen inventaris barang menggunakan **NumPy** sebagai struktur data utama. Program ini memungkinkan pengguna untuk **menambahkan barang, menampilkan daftar barang, menghitung total nilai inventaris, mencari barang berdasarkan nama atau kode, serta keluar dari program** melalui menu interaktif.

Fungsi `tambah_barang(data)` meminta input dari pengguna untuk **Nama Barang, Kode Barang, Jumlah, dan Harga Per Unit**. Untuk mencegah kesalahan input, terdapat **penanganan kesalahan (try-except)** yang memastikan **Jumlah dan Harga harus berupa angka**. Jika input tidak valid, program akan menampilkan pesan kesalahan dan tidak menambahkan data.

Fungsi `tampilkan_barang(data)` menampilkan semua barang yang tersimpan dalam array **NumPy structured array** dengan format yang rapi. Jika tidak ada barang dalam inventaris, program akan mencetak **"Kosong"**.

Fungsi `inventaris(data)` menghitung **total nilai inventaris**, yaitu hasil perkalian antara **Jumlah barang dan Harga per unit** untuk setiap barang, kemudian menjumlahkannya. Jika tidak ada data, program akan menampilkan pesan **"Data Kosong"**.

Fungsi `cari_barang(data)` memungkinkan pencarian barang berdasarkan **Nama atau Kode Barang**. Jika barang ditemukan, data barang tersebut akan ditampilkan menggunakan `tampilkan_barang()`.

Program utama menggunakan perulangan **while True** untuk menampilkan menu interaktif yang memungkinkan pengguna memilih salah satu dari lima opsi yang tersedia. Jika pengguna memilih **1-4**, program akan menjalankan fungsi yang sesuai. Jika pengguna memilih **5**, program akan keluar menggunakan `break`. Program ini menggunakan **NumPy structured array**, yang memungkinkan penyimpanan berbagai tipe data dalam satu array dan mempermudah pengolahan data inventaris.